name: Deploy to Frontend EC2

on:
  push:
    branches: [main]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
    - name: Deploy via SSH
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.EC2_HOST }}
        username: ubuntu
        key: ${{ secrets.EC2_KEY }}
        script: |
          cd /var/www/html/bahan_percobaan
          sudo git pull https://github.com/erlangga1194/bahan_percobaan.git
          sudo systemctl restart nginx
